### PR TITLE
ZCS-169 Upgrading the timezone.ics file to the latest data

### PR DESCRIPTION
**Pull request by rupalid**
Upgraded to 2017b version of the timezone data file available at https://www.iana.org/time-zones
Verified that all the changes in the timezone are reflected in timezone.ics
Updated "TzMsg.properties" and it's localized versions

### CODE REVIEW

**Review by fatkudu — CHANGES_REQUESTED** [review]
It doesn't look as if you've pulled in the latest Windows information.  Might as well do that at the same time.
See the README.md file - need to use the tool `updateWindowsNames.py` on a fully up to date Windows box and go from there.

**Comment by rupalid** [comment]
Updated the windows information in windows-names

**Review by fatkudu — COMMENTED** [review]
Do we need to add lines to the localised properties files for new timezones?  I'm guessing yes - which would mean that a full fix would require localizations.

**Review by fatkudu — APPROVED** [review]
I'm tempted to think the localization issue can be handled separately with a different bug, hence approving of this.

**Review by shrikant-prasad — APPROVED** [review]

**Pull request closed without merging**
